# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-16 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', 'man'), ('female', 'woman')], default='male', max_length=12)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-c_time'],
                'db_table': 'userinfo',
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['c_time'], name='create_time'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name', 'email'], name='idx_name_email'),
        ),
    ]
