# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-19 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsite', '0002_auto_20190418_2138'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='userinfo_c_time_a18952_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='userinfo_name_399b88_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['c_time'], name='create_time'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name', 'email'], name='idx_name_email'),
        ),
    ]
